Repository starkware-libs/starkware-starknet-utils, pull requests merged in 2025-03, with the labels that each got.

#39 feat(trace): penultimate function
  src/trace/errors.cairo
  src/trace/mock.cairo
  src/trace/test.cairo
  src/trace/trace.cairo
Labels: autoupdate

#41 feat(cairo): mintable token interface
  src/interfaces.cairo
  src/interfaces/mintable_token.cairo
Labels: autoupdate-rebase

#42 feat(testing): move consts
  packages/testing/src/constants.cairo
  packages/testing/src/lib.cairo
  src/components/roles/test.cairo
  src/components/roles/test_utils.cairo
Labels: autoupdate-rebase

#40 fix(trace): rename pos to len
  src/trace/mock.cairo
  src/trace/test.cairo
  src/trace/trace.cairo
Labels: autoupdate

#43 chore(cairo): organize packages
  Scarb.lock
  Scarb.toml
  packages/testing/README.md
  packages/testing/Scarb.toml
Labels: autoupdate-rebase

#54 Release v0.1.1
  Scarb.lock
  Scarb.toml
Labels: release

#55 Release v0.1.1
  .github/workflows/publish-testing.yml
  .github/workflows/publish.yml
Labels: release

#56 Release v0.1.1
  .github/workflows/publish-testing.yml
  .github/workflows/publish.yml
Labels: release

#59 feat(trace): remove deref
  packages/utils/src/trace/mock.cairo
  packages/utils/src/trace/trace.cairo
Labels: autoupdate
